# Generated by Django 6.0.3 on 2026-04-07 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjBackend', '0003_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('objet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjBackend.objet')),
            ],
        ),
    ]
