# Generated by Django 6.0.3 on 2026-04-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjBackend', '0005_centre_zone_adminlog_factureia'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=123456, max_length=100),
            preserve_default=False,
        ),
    ]
