# Generated by Django 6.0.3 on 2026-04-17 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjBackend', '0006_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='objet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='objets/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
