# Generated by Django 6.0.3 on 2026-04-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjBackend', '0007_objet_image_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='objet',
            name='categorie',
            field=models.CharField(default='autre', max_length=50),
        ),
    ]
