# Generated by Django 6.0.4 on 2026-05-06 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjBackend', '0009_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('objet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjBackend.objet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjBackend.user')),
            ],
            options={
                'unique_together': {('user', 'objet')},
            },
        ),
    ]
