# Generated by Django 6.0.4 on 2026-05-11 10:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjBackend', '0013_user_is_online_user_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='lieu_naissance',
        ),
        migrations.RemoveField(
            model_name='document',
            name='lieu_perte',
        ),
        migrations.RemoveField(
            model_name='document',
            name='numero_document',
        ),
        migrations.AddField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='lieu_trouve',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='nni',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='telephone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
