# Generated by Django 6.0.4 on 2026-05-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjBackend', '0015_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='statut',
            field=models.CharField(default='trouvé', max_length=50),
        ),
    ]
